### ISSUE TITLE
Payment module

### ISSUE THREAD

**Issue by ezekielchow** [ezekielchow/tzetypes-badminton#4]
### Phase 1 - Club Owners
- [ ] Club owners pay for a subscription to register their club. They can choose different subscription levels according to the size or requirements of their club.
- [ ] Exclusive right for club owners to start/organize games, encouraging more club sign-ups.
- [ ] Game statistics are publicly accessible and can be viewed by anyone possessing the link. This fosters transparency and can be a way to attract new users.
- [ ] Club members and players can bookmark game statistics. This can act as an incentive for player payments in phase 2.

### Phase 1 Onboarding 
- [ ] Approach club owners with free trial for certain period for beta testing
- [ ] Players can register freely, but will be limited to viewing bookmarked games, without in-depth game analysis

### Phase 2 - Players
- [ ] Players have the option to pay for a premium subscription which includes advanced features such as in-depth game analysis. This can explore patterns in their bookmarked matches, personal performance trends, and provide personalized improvement suggestions.
- [ ] After a certain time frame or level of engagement, players obtain the privilege to start and host their own games.

### Phase 2 Onboarding
- [ ] In depth game analysis, based on the length of matches and points, give analysis
- [ ] Based on the history of matches, give positive based prediction using AI. For example, high chance to win if game goes below 30 minutes, lower chance if game goes after 30 minutes
